
package pimsgui;
import javax.swing.*;
import java .io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.io.BufferedReader;
public class ADDFRAME extends javax.swing.JFrame {
     /**
     * Creates new form ADDFRAME
     */
    public ADDFRAME() {
        initComponents();
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        register_txt = new javax.swing.JLabel();
        id_l = new javax.swing.JLabel();
        id_tf = new javax.swing.JTextField();
        name_l = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        sex_l = new javax.swing.JLabel();
        rdb_men = new javax.swing.JRadioButton();
        rdb_female = new javax.swing.JRadioButton();
        Dob_l = new javax.swing.JLabel();
        Dob_tf = new javax.swing.JTextField();
        crime_l = new javax.swing.JLabel();
        crime_tf = new javax.swing.JTextField();
        sent_l = new javax.swing.JLabel();
        sent_tf = new javax.swing.JTextField();
        medh_l = new javax.swing.JLabel();
        MD_tb = new javax.swing.JScrollPane();
        MD_tbx = new javax.swing.JTextArea();
        reld_l = new javax.swing.JLabel();
        reld_tf = new javax.swing.JTextField();
        cell_l = new javax.swing.JLabel();
        cell_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        VISI_tb = new javax.swing.JTextArea();
        back_but = new javax.swing.JButton();
        save_but = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        footer_l = new javax.swing.JLabel();
    buttonGroup1.add(rdb_men);
    buttonGroup1.add(rdb_female);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        register_txt.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        register_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register_txt.setText("REGISTER FORM");
        register_txt.setOpaque(true);

        id_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        id_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_l.setText("ENTER ID NO : ");

        id_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_tfActionPerformed(evt);
            }
        });

        name_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        name_l.setText("ENTER NAME : ");

        name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_tfActionPerformed(evt);
            }
        });

        sex_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sex_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sex_l.setText("SEX");

        rdb_men.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        rdb_men.setText("MEN");
        rdb_men.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_menActionPerformed(evt);
            }
        });

        rdb_female.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        rdb_female.setText("FEMALE");
        rdb_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_femaleActionPerformed(evt);
            }
        });

        Dob_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Dob_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dob_l.setText("DATE OF BIRTH : ");

        Dob_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dob_tfActionPerformed(evt);
            }
        });

        crime_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        crime_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crime_l.setText("CRIME : ");

        crime_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crime_tfActionPerformed(evt);
            }
        });

        sent_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sent_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sent_l.setText("SENTENCE(YEAR) : ");

        sent_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sent_tfActionPerformed(evt);
            }
        });

        medh_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        medh_l.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        medh_l.setText("MEDICAL HISTORY : ");

        MD_tbx.setColumns(20);
        MD_tbx.setRows(5);
        MD_tbx.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                MD_tbxInputMethodTextChanged(evt);
            }
        });
        MD_tb.setViewportView(MD_tbx);

        reld_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        reld_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reld_l.setText("RELEASE DATE : ");

        reld_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reld_tfActionPerformed(evt);
            }
        });

        cell_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cell_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell_l.setText("CELL NUMBER : ");

        cell_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell_tfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VISITORS : ");

        VISI_tb.setColumns(20);
        VISI_tb.setRows(5);
        VISI_tb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                VISI_tbInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(VISI_tb);

        back_but.setBackground(new java.awt.Color(0, 51, 204));
        back_but.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back_but.setForeground(new java.awt.Color(255, 255, 255));
        back_but.setText("BACK");
        back_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_butActionPerformed(evt);
            }
        });

        save_but.setBackground(new java.awt.Color(0, 51, 204));
        save_but.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save_but.setForeground(new java.awt.Color(255, 255, 255));
        save_but.setText("SAVE");
        save_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        footer_l.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        footer_l.setForeground(new java.awt.Color(51, 153, 255));
        footer_l.setText("prisoner information managment system");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(sex_l, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(crime_l, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(medh_l)
                                                .addGap(10, 10, 10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(cell_l, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdb_men)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdb_female))
                                    .addComponent(cell_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(crime_tf)
                                    .addComponent(MD_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(id_l)
                                .addGap(18, 18, 18)
                                .addComponent(id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back_but, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reld_l, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sent_l)
                                    .addComponent(Dob_l)
                                    .addComponent(name_l, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sent_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Dob_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(reld_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(save_but, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(register_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(footer_l, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(register_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_l)
                    .addComponent(id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_l, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sex_l, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdb_men)
                        .addComponent(rdb_female))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Dob_tf)
                        .addComponent(Dob_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crime_l, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crime_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sent_l, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(sent_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(medh_l, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MD_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cell_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cell_l, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reld_l, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reld_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_but, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_but, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(footer_l)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void rdb_menActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void reld_tfActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cell_tfActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void Dob_tfActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void id_tfActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void name_tfActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void rdb_femaleActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void crime_tfActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void sent_tfActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void MD_tbxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void VISI_tbInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void back_butActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        MAIN_MENU men=new MAIN_MENU();
        men.setVisible(true);
        
        this.setVisible(false);
    }                                        

private void save_butActionPerformed(java.awt.event.ActionEvent evt) {
    // Get the data from the form fields
    String id = id_tf.getText().trim();
    String name = name_tf.getText().trim();
    String sex = rdb_men.isSelected() ? "Male" : (rdb_female.isSelected() ? "Female" : "");
    String dob = Dob_tf.getText().trim();
    String crime = crime_tf.getText().trim();
    String sentence = sent_tf.getText().trim();
    String medicalHistory = MD_tbx.getText().trim();
    String releaseDate = reld_tf.getText().trim();
    String cellNumber = cell_tf.getText().trim();
    String visitors = VISI_tb.getText().trim();

    // Validate the form fields
    if (id.isEmpty() || name.isEmpty() || sex.isEmpty() || dob.isEmpty() || crime.isEmpty() ||
        sentence.isEmpty() || medicalHistory.isEmpty() || releaseDate.isEmpty() || cellNumber.isEmpty() || visitors.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required. Please fill in all the information.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop the save operation if any field is blank
    }

    // Validate Cell Number (must be a valid integer)
    try {
        int cellNumberInt = Integer.parseInt(cellNumber); // Try to parse the cell number as an integer
        if (cellNumberInt <= 0) {
            JOptionPane.showMessageDialog(this, "Cell Number must be a positive integer.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop the save operation if the cell number is not a positive integer
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Cell Number must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop the save operation if the cell number is not a valid integer
    }

    // Check if the ID already exists in the file
    boolean idExists = false;
    try (BufferedReader reader = new BufferedReader(new FileReader("C:\\PIMS\\CURRENT_DB.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.startsWith("ID: " + id)) {
                idExists = true;
                break;
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading CURRENT_DB.txt file.", "File Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        return;
    }

    if (idExists) {
        JOptionPane.showMessageDialog(this, "ID already exists in the database. Please enter a unique ID.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop the save operation if the ID already exists
    }

    // Prepare the data to be saved
    String data = String.format(
        "ID: %s\nName: %s\nSex: %s\nDate of Birth: %s\nCrime: %s\nSentence: %s\nMedical History: %s\nRelease Date: %s\nCell Number: %s\nVisitors: %s\n",
        id, name, sex, dob, crime, sentence, medicalHistory, releaseDate, cellNumber, visitors
    );

    // Write the data to a file
    try (java.io.FileWriter writer = new java.io.FileWriter("C:\\PIMS\\CURRENT_DB.txt", true)) {
        writer.write(data + "\n"); // Append the data to the file
        JOptionPane.showMessageDialog(this, "Data saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (java.io.IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
} 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pims.ADDFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pims.ADDFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pims.ADDFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pims.ADDFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pims.ADDFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Dob_l;
    private javax.swing.JTextField Dob_tf;
    private javax.swing.JScrollPane MD_tb;
    private javax.swing.JTextArea MD_tbx;
    private javax.swing.JTextArea VISI_tb;
    private javax.swing.JButton back_but;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel cell_l;
    private javax.swing.JTextField cell_tf;
    private javax.swing.JLabel crime_l;
    private javax.swing.JTextField crime_tf;
    private javax.swing.JLabel footer_l;
    private javax.swing.JLabel id_l;
    private javax.swing.JTextField id_tf;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel medh_l;
    private javax.swing.JLabel name_l;
    private javax.swing.JTextField name_tf;
    private javax.swing.JRadioButton rdb_female;
    private javax.swing.JRadioButton rdb_men;
    private javax.swing.JLabel register_txt;
    private javax.swing.JLabel reld_l;
    private javax.swing.JTextField reld_tf;
    private javax.swing.JButton save_but;
    private javax.swing.JLabel sent_l;
    private javax.swing.JTextField sent_tf;
    private javax.swing.JLabel sex_l;
    // End of variables declaration 
}
