/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package pimsgui;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author COMPUTER
 */
public class EDIT_FRAME extends javax.swing.JFrame {
       /**
     * Creates new form EDIT_FRAME
     */
    public EDIT_FRAME() {
        initComponents();
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        edit_info_l = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        note_l = new javax.swing.JLabel();
        ID_l = new javax.swing.JLabel();
        Id_tf = new javax.swing.JTextField();
        name_l = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        sex_l = new javax.swing.JLabel();
        men_rb = new javax.swing.JRadioButton();
        female_rb = new javax.swing.JRadioButton();
        dob_l = new javax.swing.JLabel();
        dob_tf = new javax.swing.JTextField();
        crime_l = new javax.swing.JLabel();
        crime_tf = new javax.swing.JTextField();
        sent_l = new javax.swing.JLabel();
        sent_tf = new javax.swing.JTextField();
        md_h_l = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MD_tbx = new javax.swing.JTextArea();
        reld_l = new javax.swing.JLabel();
        reld_tf = new javax.swing.JTextField();
        cell_l = new javax.swing.JLabel();
        cell_tf = new javax.swing.JTextField();
        visitors_l = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        visit_tbx = new javax.swing.JTextArea();
        back_but = new javax.swing.JButton();
        save_but = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");
        javax.swing.ButtonGroup sexButtonGroup = new javax.swing.ButtonGroup();

    // Add the radio buttons to the ButtonGroup
    sexButtonGroup.add(men_rb);
    sexButtonGroup.add(female_rb);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edit_info_l.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit_info_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_info_l.setText("EDIT PRISONER INFORMATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        note_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        note_l.setText("NOTE: If You Don't Want To Update Some Datas Leave Blank And  Click Save Button!!");

        ID_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID_l.setText("ENETER ID : ");

        Id_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_tfActionPerformed(evt);
            }
        });

        name_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        name_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_l.setText("ENTER NAME : ");

        name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_tfActionPerformed(evt);
            }
        });

        sex_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sex_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sex_l.setText("SEX : ");

        men_rb.setText("MEN");
        men_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_rbActionPerformed(evt);
            }
        });

        female_rb.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        female_rb.setText("FEMALE");
        female_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_rbActionPerformed(evt);
            }
        });

        dob_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dob_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dob_l.setText("DATE OF BIRTH : ");

        dob_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob_tfActionPerformed(evt);
            }
        });

        crime_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        crime_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crime_l.setText("CRIME : ");

        crime_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crime_tfActionPerformed(evt);
            }
        });

        sent_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sent_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sent_l.setText("SENTENCE(YEAR) : ");

        sent_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sent_tfActionPerformed(evt);
            }
        });

        md_h_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        md_h_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        md_h_l.setText("MEDICAL HISTORY : ");

        MD_tbx.setColumns(20);
        MD_tbx.setRows(5);
        MD_tbx.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                MD_tbxInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(MD_tbx);

        reld_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        reld_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reld_l.setText("RELEASE DATE :  ");

        reld_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reld_tfActionPerformed(evt);
            }
        });

        cell_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cell_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cell_l.setText("CELL NO : ");

        cell_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell_tfActionPerformed(evt);
            }
        });

        visitors_l.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        visitors_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visitors_l.setText("VISITORS : ");

        visit_tbx.setColumns(20);
        visit_tbx.setRows(5);
        visit_tbx.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                visit_tbxInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(visit_tbx);

        back_but.setBackground(new java.awt.Color(0, 51, 204));
        back_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back_but.setForeground(new java.awt.Color(255, 255, 255));
        back_but.setText("BACK TO MENU");
        back_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_butActionPerformed(evt);
            }
        });

        save_but.setBackground(new java.awt.Color(0, 51, 204));
        save_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        save_but.setForeground(new java.awt.Color(255, 255, 255));
        save_but.setText("SAVE");
        save_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_butActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("prisoner information managment system");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID_l, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sex_l, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(note_l, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Id_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dob_l)
                                            .addComponent(name_l, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dob_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(crime_l, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(men_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(female_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(crime_tf)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cell_l, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(md_h_l))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(cell_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                            .addComponent(back_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(reld_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(sent_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(visitors_l, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sent_tf)
                                            .addComponent(reld_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(save_but, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(edit_info_l, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(edit_info_l, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(note_l, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ID_l, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Id_tf)
                        .addComponent(name_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(md_h_l, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sex_l, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(men_rb)
                                        .addComponent(female_rb))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(crime_l, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(crime_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cell_l, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cell_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(visitors_l, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dob_l, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sent_l, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sent_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reld_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reld_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save_but, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_but, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>                        

    private void name_tfActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void dob_tfActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void crime_tfActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void reld_tfActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void Id_tfActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void men_rbActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void female_rbActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void sent_tfActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void MD_tbxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void cell_tfActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void visit_tbxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void back_butActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:\
         MAIN_MENU men=new MAIN_MENU();
        men.setVisible(true);
        
        this.dispose();
    }                                        

   private void save_butActionPerformed(java.awt.event.ActionEvent evt) {                                         
    // Get the ID from the ID text field
    String id = Id_tf.getText().trim();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Read the entire file into memory
    List<String> lines = new ArrayList<>();
    try (BufferedReader reader = new BufferedReader(new FileReader("C:\\PIMS\\CURRENT_DB.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            lines.add(line);
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading CURRENT_DB.txt file.", "File Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        return;
    }

    // Find the prisoner's record and update it
    boolean recordFound = false;
    for (int i = 0; i < lines.size(); i++) {
        if (lines.get(i).startsWith("ID: " + id)) {
            recordFound = true;

            // Update the fields if they are not empty
            if (!name_tf.getText().trim().isEmpty()) {
                lines.set(i + 1, "Name: " + name_tf.getText().trim());
            }
            if (men_rb.isSelected()) {
                lines.set(i + 2, "Sex: Male");
            } else if (female_rb.isSelected()) {
                lines.set(i + 2, "Sex: Female");
            }
            if (!dob_tf.getText().trim().isEmpty()) {
                lines.set(i + 3, "Date of Birth: " + dob_tf.getText().trim());
            }
            if (!crime_tf.getText().trim().isEmpty()) {
                lines.set(i + 4, "Crime: " + crime_tf.getText().trim());
            }
            if (!sent_tf.getText().trim().isEmpty()) {
                lines.set(i + 5, "Sentence: " + sent_tf.getText().trim());
            }
            if (!reld_tf.getText().trim().isEmpty()) {
                lines.set(i + 6, "Release Date: " + reld_tf.getText().trim());
            }
            if (!cell_tf.getText().trim().isEmpty()) {
                lines.set(i + 7, "Cell Number: " + cell_tf.getText().trim());
            }
            if (!MD_tbx.getText().trim().isEmpty()) {
                lines.set(i + 8, "Medical History: " + MD_tbx.getText().trim());
            }
            if (!visit_tbx.getText().trim().isEmpty()) {
                lines.set(i + 9, "Visitors: " + visit_tbx.getText().trim());
            }
            break;
        }
    }

    if (!recordFound) {
        JOptionPane.showMessageDialog(this, "ID not found in the database.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Write the updated data back to the file
    try (BufferedWriter writer = new BufferedWriter(new FileWriter("C:\\PIMS\\CURRENT_DB.txt"))) {
        for (String line : lines) {
            writer.write(line);
            writer.newLine();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error writing to CURRENT_DB.txt file.", "File Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        return;
    }

    // Display success message
    JOptionPane.showMessageDialog(this, "Prisoner information updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDIT_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDIT_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDIT_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDIT_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDIT_FRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel ID_l;
    private javax.swing.JTextField Id_tf;
    private javax.swing.JTextArea MD_tbx;
    private javax.swing.JButton back_but;
    private javax.swing.JLabel cell_l;
    private javax.swing.JTextField cell_tf;
    private javax.swing.JLabel crime_l;
    private javax.swing.JTextField crime_tf;
    private javax.swing.JLabel dob_l;
    private javax.swing.JTextField dob_tf;
    private javax.swing.JLabel edit_info_l;
    private javax.swing.JRadioButton female_rb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel md_h_l;
    private javax.swing.JRadioButton men_rb;
    private javax.swing.JLabel name_l;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel note_l;
    private javax.swing.JLabel reld_l;
    private javax.swing.JTextField reld_tf;
    private javax.swing.JButton save_but;
    private javax.swing.JLabel sent_l;
    private javax.swing.JTextField sent_tf;
    private javax.swing.JLabel sex_l;
    private javax.swing.JTextArea visit_tbx;
    private javax.swing.JLabel visitors_l;
    // End of variables declaration       
}
