
package pimsgui;

public class MAIN_MENU extends javax.swing.JFrame {
       /**
     * Creates new form MAIN_MENU
     */
    public MAIN_MENU() {
        initComponents();
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        main_l = new javax.swing.JLabel();
        add_but = new javax.swing.JButton();
        edit_butt = new javax.swing.JButton();
        display_but = new javax.swing.JButton();
        search_but = new javax.swing.JButton();
        del_but = new javax.swing.JButton();
        display_or_trans_but = new javax.swing.JButton();
        logout_but = new javax.swing.JButton();
        discat_but = new javax.swing.JButton();
        footer_l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        main_l.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        main_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main_l.setText("MAIN MENU");

        add_but.setBackground(new java.awt.Color(0, 51, 204));
        add_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        add_but.setForeground(new java.awt.Color(255, 255, 255));
        add_but.setText("REGISTER ");
        add_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_butActionPerformed(evt);
            }
        });

        edit_butt.setBackground(new java.awt.Color(0, 51, 204));
        edit_butt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        edit_butt.setForeground(new java.awt.Color(255, 255, 255));
        edit_butt.setText("EDIT INFORMATION");
        edit_butt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttActionPerformed(evt);
            }
        });

        display_but.setBackground(new java.awt.Color(0, 51, 204));
        display_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        display_but.setForeground(new java.awt.Color(255, 255, 255));
        display_but.setText("DISPLAY ALL ");
        display_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        display_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_butActionPerformed(evt);
            }
        });

        search_but.setBackground(new java.awt.Color(0, 51, 204));
        search_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        search_but.setForeground(new java.awt.Color(255, 255, 255));
        search_but.setText("SEARCH");
        search_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_butActionPerformed(evt);
            }
        });

        del_but.setBackground(new java.awt.Color(0, 51, 204));
        del_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        del_but.setForeground(new java.awt.Color(255, 255, 255));
        del_but.setText("DELETE OR TRANSFER");
        del_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        del_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_butActionPerformed(evt);
            }
        });

        display_or_trans_but.setBackground(new java.awt.Color(0, 51, 204));
        display_or_trans_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        display_or_trans_but.setForeground(new java.awt.Color(255, 255, 255));
        display_or_trans_but.setText("DISPLAY TRANSFERED OR DELETED ");
        display_or_trans_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        display_or_trans_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_or_trans_butActionPerformed(evt);
            }
        });

        logout_but.setBackground(new java.awt.Color(0, 51, 204));
        logout_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        logout_but.setForeground(new java.awt.Color(255, 255, 255));
        logout_but.setText("LOGOUT");
        logout_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_butActionPerformed(evt);
            }
        });

        discat_but.setBackground(new java.awt.Color(0, 51, 204));
        discat_but.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        discat_but.setForeground(new java.awt.Color(255, 255, 255));
        discat_but.setText("DISPLAY BY CRIME CATAGORY");
        discat_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        discat_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discat_butActionPerformed(evt);
            }
        });

        footer_l.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        footer_l.setForeground(new java.awt.Color(51, 153, 255));
        footer_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footer_l.setText("prisoner information managment system");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(add_but, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edit_butt, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(display_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(search_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(logout_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(display_or_trans_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(discat_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(del_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(126, 126, 126))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(main_l, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(footer_l, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(main_l, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_but, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(del_but, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_butt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discat_but, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display_but, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display_or_trans_but, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_but, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout_but, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(footer_l)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void add_butActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        ADDFRAME add=new ADDFRAME();
        add.setVisible(true);
        this.setVisible(false);
        
    }                                       

    private void search_butActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        SEARCH_BY_ID search=new SEARCH_BY_ID();
        search.setVisible(true);
         this.setVisible(false);
    }                                          

    private void del_butActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
         DELETE_OR_TRANSFER_FRAME del=new  DELETE_OR_TRANSFER_FRAME();
         del.setVisible(true);
         
         this.setVisible(false);
    }                                       

    private void display_or_trans_butActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        DISPLAY_TRANS_OR_DELETE_FRAME dot=new DISPLAY_TRANS_OR_DELETE_FRAME();
        dot.setVisible(true);
         this.setVisible(false);
    }                                                    

    private void discat_butActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        CHOICE_CATAGORY ch=new CHOICE_CATAGORY();
        ch.setVisible(true);
        
         this.setVisible(false);
    }                                          

    private void display_butActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        DISPLAY_ALL_FRAME dis=new DISPLAY_ALL_FRAME();
        dis.setVisible(true);
         this.setVisible(false);
    }                                           

   private void edit_buttActionPerformed(java.awt.event.ActionEvent evt) {                                            
    // Open the EDIT_FRAME if the ID exists
    EDIT_FRAME edit = new EDIT_FRAME();
    edit.setVisible(true);
     this.setVisible(false);
}                                     

    private void logout_butActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        LOGIN_FORM log=new LOGIN_FORM();
        log.setVisible(true);
        
        this.dispose();
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pims.MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pims.MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pims.MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pims.MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pims.MAIN_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton add_but;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton del_but;
    private javax.swing.JButton discat_but;
    private javax.swing.JButton display_but;
    private javax.swing.JButton display_or_trans_but;
    private javax.swing.JButton edit_butt;
    private javax.swing.JLabel footer_l;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout_but;
    private javax.swing.JLabel main_l;
    private javax.swing.JButton search_but;
    // End of variables declaration                       
}


